# Generated by Django 5.0 on 2024-07-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ceo',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=21),
        ),
    ]
