# Generated by Django 5.0 on 2024-05-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employeee',
            new_name='Employee',
        ),
    ]
